@startuml

package "Domain" {
    rectangle "Aggregates" as aggregates
    rectangle "Domain Services" as domain_services
}

database "Database" as db

rectangle "Infra" {
    rectangle Web {
        rectangle "Async API\nsocket.io" as async
        rectangle "Sync API\nHTTP" as http
    }
    rectangle "Repositories" as repositories
    queue "Event Bus" as event_bus
}

domain_services --> aggregates
event_bus ---> domain_services

domain_services -u--> repositories

domain_services <-> async

repositories --> db

repositories -> event_bus


http->domain_services

actor "Player" as player

player <--> async
player --> http

rectangle "Frontend assets" as assets

http --> assets

@enduml