name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Perform CI
        run: ./mage.sh ci
      - name: Update coverage
        uses: codecov/codecov-action@v2
